language: node_js
node_js:
  - 11

cache:
  npm: true
  yarn: true
  directories:
    - node_modules
    - ~/.cache

install:
  - yarn

script:
  - yarn lint
  - yarn test --run-in-band
  - yarn e2e --headless
